# Generated by Django 4.2.30 on 2026-06-13 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='emailanalysisrecord',
            new_name='dashboard_e_user_id_eff266_idx',
            old_name='dashboard_e_user_id_3a1f5c_idx',
        ),
        migrations.RenameIndex(
            model_name='emailanalysisrecord',
            new_name='dashboard_e_user_id_dac5cd_idx',
            old_name='dashboard_e_user_id_8c2b41_idx',
        ),
    ]
