# Generated by Django 4.2.30 on 2026-06-13 17:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(db_index=True, max_length=512, unique=True)),
                ('thread_id', models.CharField(blank=True, db_index=True, max_length=256)),
                ('sender_name', models.CharField(blank=True, max_length=256)),
                ('sender_email', models.EmailField(db_index=True, max_length=320)),
                ('sender_domain', models.CharField(blank=True, db_index=True, max_length=253)),
                ('recipients_to', models.JSONField(default=list)),
                ('recipients_cc', models.JSONField(default=list)),
                ('recipients_bcc', models.JSONField(default=list)),
                ('subject', models.TextField(blank=True)),
                ('body_plain', models.TextField(blank=True)),
                ('body_html', models.TextField(blank=True)),
                ('snippet', models.CharField(blank=True, max_length=512)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('has_attachments', models.BooleanField(default=False)),
                ('attachment_count', models.PositiveSmallIntegerField(default=0)),
                ('raw_headers', models.JSONField(default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('labels', models.JSONField(default=list)),
                ('risk_score', models.FloatField(blank=True, null=True)),
                ('is_flagged', models.BooleanField(default=False)),
                ('flag_reason', models.CharField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['sender_domain', 'received_at'], name='emails_emai_sender__bf78da_idx'), models.Index(fields=['is_flagged', 'received_at'], name='emails_emai_is_flag_5491c3_idx')],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=512)),
                ('mime_type', models.CharField(blank=True, max_length=256)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('attachment_id', models.CharField(blank=True, max_length=256)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='emails.email')),
            ],
        ),
    ]
