# Generated by Django 4.2.30 on 2026-06-13 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gmail', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='emailmessage',
            new_name='gmail_email_account_c2a59f_idx',
            old_name='gmail_email_account_date_idx',
        ),
        migrations.RenameIndex(
            model_name='emailmessage',
            new_name='gmail_email_account_656eff_idx',
            old_name='gmail_email_account_risk_idx',
        ),
        migrations.RenameIndex(
            model_name='emailmessage',
            new_name='gmail_email_domain_001e98_idx',
            old_name='gmail_email_domain_idx',
        ),
    ]
