# Generated by Django 4.2.30 on 2026-06-13 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmail', '0002_rename_gmail_email_account_date_idx_gmail_email_account_c2a59f_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='hasMaliciousUrl',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='hasPhishingUrl',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='urlScanSummary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='urlScore',
            field=models.IntegerField(default=0),
        ),
    ]
