# Generated by Django 4.2.30 on 2026-06-14 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmail', '0003_emailmessage_hasmaliciousurl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmessage',
            name='aiSummary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='body',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='domain',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='domainAge',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='senderName',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='subject',
            field=models.TextField(blank=True, default=''),
        ),
    ]
