# Generated by Django 4.2.30 on 2026-06-14 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmail', '0004_alter_emailmessage_aisummary_alter_emailmessage_body_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailmessage',
            name='hasMaliciousUrl',
        ),
        migrations.RemoveField(
            model_name='emailmessage',
            name='hasPhishingUrl',
        ),
        migrations.RemoveField(
            model_name='emailmessage',
            name='urlScanSummary',
        ),
        migrations.RemoveField(
            model_name='emailmessage',
            name='urlScore',
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='aiSummary',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='domain',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='domainAge',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='senderName',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='subject',
            field=models.TextField(blank=True),
        ),
    ]
