# Generated by Django 4.2.30 on 2026-06-13 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmail_message_id', models.CharField(db_index=True, help_text='Gmail API message ID used to look up cached results.', max_length=255, unique=True)),
                ('urgency', models.PositiveSmallIntegerField(default=0)),
                ('fear', models.PositiveSmallIntegerField(default=0)),
                ('credential_theft', models.PositiveSmallIntegerField(default=0)),
                ('financial_fraud', models.PositiveSmallIntegerField(default=0)),
                ('authority_impersonation', models.PositiveSmallIntegerField(default=0)),
                ('ai_summary', models.TextField(blank=True)),
                ('ai_score', models.PositiveSmallIntegerField(default=0, help_text='Weighted composite of the five threat dimensions (0-100).')),
                ('domain_score', models.PositiveSmallIntegerField(default=0, help_text='Score from domain reputation analysis (0-100).')),
                ('threat_score', models.PositiveSmallIntegerField(default=0, help_text='Final score: aiScore*0.70 + domainScore*0.30 (0-100).')),
                ('risk_level', models.CharField(choices=[('Critical', 'Critical'), ('High', 'High'), ('Medium', 'Medium'), ('Safe', 'Safe')], default='Safe', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email Analysis Result',
                'verbose_name_plural': 'Email Analysis Results',
                'ordering': ['-created_at'],
            },
        ),
    ]
