# Generated by Django 4.2.30 on 2026-06-13 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreatAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_score', models.PositiveSmallIntegerField(help_text='0-100 Gemini-derived risk score (apps.analysis).')),
                ('domain_score', models.PositiveSmallIntegerField(help_text='0-100 domain reputation risk score (apps.reputation).')),
                ('threat_score', models.PositiveSmallIntegerField(help_text='round(aiScore * 0.7 + domainScore * 0.3), 0-100.')),
                ('risk_level', models.CharField(choices=[('Safe', 'Safe'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], help_text='One of "Critical" | "High" | "Medium" | "Safe".', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='threat_assessment', to='emails.email')),
            ],
            options={
                'ordering': ['-threat_score'],
                'indexes': [models.Index(fields=['risk_level'], name='threats_thr_risk_le_19f1dc_idx'), models.Index(fields=['threat_score'], name='threats_thr_threat__1b5a6b_idx')],
            },
        ),
    ]
